from __future__ import absolute_import
from .ddpg import DDPGAgent
from .ddpg_n1 import DDPGAgent_n1
from .ddpg_t1 import DDPGAgent_t1
from .ddpg_t2 import DDPGAgent_t2
from .ddpg_t2p import DDPGAgent_t2p
from .ddpg_t2p_kfac import DDPGAgent_t2p_kfac
from .ddpg_t2r import DDPGAgent_t2r
from .ddpg_t3 import DDPGAgent_t3